import { tv } from 'tailwind-variants';

import { Tabs } from '@/app/_components/tabs';
import { AddButton } from '@/app/chef/[chefId]/_components/add-button';

export const metadata = {
  title: 'シェフ詳細',
  description: 'Generated by create next app',
};

const layout = tv({
  base: 'm-auto flex max-w-[400px] flex-col gap-5', // TODO: ここでmax-wを指定せずサイドバーと合わせて指定した方がよさそう
});

export default async function Layout({
  params,
  children,
}: {
  params: { chefId: string };
  children: React.ReactNode;
}) {
  const { chefId } = params;

  const tabs = [
    {
      path: `/chef/${chefId}/new-recipes`,
      tabText: '新着レシピ',
    },
    {
      path: `/chef/${chefId}/hot-recipes`,
      tabText: '人気レシピ',
    },
  ];

  return (
    <main className={layout()}>
      <div className='flex flex-col justify-center gap-1 self-stretch'>
        <p className='text-2xl font-bold text-mauve-12'>山田シェフ</p>
        <p className='text-sm text-mauve-12'>foobarid</p>
      </div>
      <div className='flex gap-4 self-stretch'>
        <div className='flex items-center gap-1'>
          <p className='text-sm font-bold text-mauve-11'>123</p>
          <p className='text-sm text-mauve-11'>レシピ</p>
        </div>
        <div className='flex items-center gap-1'>
          <p className='text-sm font-bold text-mauve-11'>456</p>
          <p className='text-sm text-mauve-11'>フォロワー</p>
        </div>
      </div>
      <button className='rounded-md border border-mauve-12 px-3 py-1'>
        プロフィールを編集
      </button>
      <div>
        <Tabs tabs={tabs} />
        {children}
        <div className='fixed bottom-7 translate-x-24'>
          <AddButton />
        </div>
      </div>
    </main>
  );
}
