import { MdFavoriteBorder, MdArrowBack } from 'react-icons/md';
import { tv } from 'tailwind-variants';

import { RecipeTabs } from '@/app/_components/recipe-tabs';

const recipeTab = tv({
  slots: {
    main: 'm-auto max-w-[400px]',
    imageArea: 'h-[400px] w-[400px] bg-red-200',
    back: 'absolute left-[20px] top-[20px] h-[32px] w-[32px]',
    backIcon: 'h-[32px] w-[32px] text-[#fff]',
    fav: 'absolute bottom-0 left-[320px] top-[340px] h-[60px] w-[60px] rounded-full bg-[#908E96]',
    favArea: 'absolute left-[12px] top-[14px] h-[36px] w-[36px]',
    favIcon: 'h-[36px] w-[36px] text-[#fff]',
    recipeName: 'm-4 text-[28px] font-bold',
  },
});

const { main, imageArea, back, backIcon, fav, favArea, favIcon, recipeName } =
  recipeTab();

export const metadata = {
  title: 'レシピ詳細',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  // TODO: レシピ詳細取得
  return (
    <main className={main()}>
      {/* 料理画像 */}
      <div className='relative'>
        <div className={imageArea()} />
        <div className={back()}>
          <MdArrowBack className={backIcon()} />
        </div>
        <div className={fav()}>
          <div className={favArea()}>
            {/* TODO: Favo/Unfavoの切り替え */}
            <MdFavoriteBorder className={favIcon()} />
          </div>
        </div>
      </div>
      {/* 料理名、説明文 */}
      <div>
        <p className={recipeName()}>グラタン</p>
        <p className='m-4'>
          はじめてでも失敗なく作れるような、鶏肉や玉ねぎを具とした基本的なマカロニグラタンのレシピです。
          ソースと具材炒めを別器具で行うレシピも多いですが、グラタンの具を炒めたフライパンの中で、そのままホワイトソースを仕上げる手軽な作り方にしています。ぜひお試しください。
        </p>
        {/* お気に入り */}
        <div className='m-4 flex gap-2'>
          <p className='font-bold'>789</p>
          <p className='text-[#6F6E77]'>お気に入り</p>
        </div>
      </div>
      <RecipeTabs />
      {children}
    </main>
  );
}
